#pragma once

#define WIN32_LEAN_AND_MEAN
#define STRICT
#define NOMINMAX
#include <windows.h>

#define DIRECTDRAW_VERSION 0x0700
#include <ddraw.h>
#include <dvp.h>

#include "ddrawex.h"

#undef DDPCAPS_INITIALIZE
#undef DDSCAPS_PRIMARYSURFACELEFT
#undef DDSCAPS2_HARDWAREDEINTERLACE

#define SUGARCALL __stdcall

#define RELEASE_NONE                            0x00000000
#define RELEASE_NOTIFY                          0x00000001

#define DDEDM_NONE                              0x00000000L
#define DDEDM_VALID                             (DDEDM_REFRESHRATES | DDEDM_STANDARDVGAMODES)

#define DDENUM_NONE								0x00000000L
#define DDENUM_VALID							(DDENUM_ATTACHEDSECONDARYDEVICES \
                                                    | DDENUM_DETACHEDSECONDARYDEVICES | DDENUM_NONDISPLAYDEVICES)

#define DDGDI_NONE                              0x00000000L

#define DDSCL_NONE								0x00000000L
#define DDSCL_DONTHOOKHWND                      0x00000020L
#define DDSCL_VALID								(DDSCL_FULLSCREEN | DDSCL_ALLOWREBOOT | DDSCL_NOWINDOWCHANGES \
                                                    | DDSCL_NORMAL | DDSCL_EXCLUSIVE | DDSCL_DONTHOOKHWND \
                                                    | DDSCL_ALLOWMODEX | DDSCL_SETFOCUSWINDOW | DDSCL_SETDEVICEWINDOW \
                                                    | DDSCL_CREATEDEVICEWINDOW | DDSCL_MULTITHREADED | DDSCL_FPUSETUP | DDSCL_FPUPRESERVE)

#define DDSDM_NONE								0x00000000L
#define DDSDM_VALID								(DDSDM_STANDARDVGAMODE)

#define DDSD_NONE								0x00000000L
#define DDSD_SIZEFORMAT                         (DDSD_WIDTH | DDSD_HEIGHT | DDSD_PIXELFORMAT)
#define DDSD_VALID								(DDSD_CAPS | DDSD_HEIGHT | DDSD_WIDTH | DDSD_PITCH | DDSD_BACKBUFFERCOUNT \
                                                    | DDSD_ALPHABITDEPTH | DDSD_LPSURFACE | DDSD_PIXELFORMAT | DDSD_CKDESTOVERLAY \
                                                    | DDSD_CKDESTBLT | DDSD_CKSRCOVERLAY | DDSD_CKSRCBLT | DDSD_MIPMAPCOUNT | DDSD_REFRESHRATE \
                                                    | DDSD_LINEARSIZE | DDSD_TEXTURESTAGE | DDSD_FVF | DDSD_SRCVBHANDLE | DDSD_DEPTH)

#define DDCCAPS_NONE                            0x00000000L
#define DDCSCL_NONE                             0x00000000L
#define DDCSHWND_NONE                           0x00000000L

#define DDSCAPS_NONE							0x00000000L
#define DDSCAPS_3D								0x00000001L
#define	DDSCAPS_DATAEXCHANGE					(DDSCAPS_SYSTEMMEMORY|DDSCAPS_VIDEOMEMORY)
#define DDSCAPS_SHAREDZBUFFER                   0x01000000L
#define DDSCAPS_SHAREDBACKBUFFER                0x02000000L

#define DDSCAPS_PRIMARYSURFACELEFT              0x00000400L
#define DDSCAPS_VALID							(DDSCAPS_3D | DDSCAPS_ALPHA | DDSCAPS_BACKBUFFER | DDSCAPS_COMPLEX | DDSCAPS_FLIP \
                                                    | DDSCAPS_FRONTBUFFER | DDSCAPS_OFFSCREENPLAIN | DDSCAPS_OVERLAY | DDSCAPS_PALETTE \
                                                    | DDSCAPS_PRIMARYSURFACE | DDSCAPS_PRIMARYSURFACELEFT | DDSCAPS_SYSTEMMEMORY | DDSCAPS_TEXTURE \
                                                    | DDSCAPS_3DDEVICE | DDSCAPS_VIDEOMEMORY | DDSCAPS_VISIBLE | DDSCAPS_WRITEONLY \
                                                    | DDSCAPS_ZBUFFER | DDSCAPS_OWNDC | DDSCAPS_LIVEVIDEO | DDSCAPS_HWCODEC | DDSCAPS_MODEX \
                                                    | DDSCAPS_MIPMAP | DDSCAPS_RESERVED2 | DDSCAPS_SHAREDZBUFFER | DDSCAPS_SHAREDBACKBUFFER \
                                                    | DDSCAPS_ALLOCONLOAD | DDSCAPS_VIDEOPORT | DDSCAPS_LOCALVIDMEM | DDSCAPS_NONLOCALVIDMEM \
                                                    | DDSCAPS_STANDARDVGAMODE | DDSCAPS_OPTIMIZED)

#define DDSCAPS2_NONE							0x00000000L
#define DDSCAPS2_PERSISTENTCONTENTS             0x00000001L
#define DDSCAPS2_HARDWAREDEINTERLACE            0x00000002L
#define DDSCAPS2_DEINTERLACE                    0x08000000L
#define DDSCAPS2_VALID                          (DDSCAPS2_PERSISTENTCONTENTS | DDSCAPS2_HARDWAREDEINTERLACE | DDSCAPS2_HINTDYNAMIC | DDSCAPS2_HINTSTATIC \
                                                    | DDSCAPS2_TEXTUREMANAGE | DDSCAPS2_RESERVED1 | DDSCAPS2_RESERVED2 | DDSCAPS2_OPAQUE \
                                                    | DDSCAPS2_HINTANTIALIASING | DDSCAPS2_CUBEMAP | DDSCAPS2_CUBEMAP_ALLFACES | DDSCAPS2_MIPMAPSUBLEVEL \
                                                    | DDSCAPS2_D3DTEXTUREMANAGE | DDSCAPS2_DONOTPERSIST | DDSCAPS2_STEREOSURFACELEFT | DDSCAPS2_VOLUME \
                                                    | DDSCAPS2_NOTUSERLOCKABLE | DDSCAPS2_POINTS | DDSCAPS2_RTPATCHES | DDSCAPS2_NPATCHES | DDSCAPS2_RESERVED3 \
                                                    | DDSCAPS2_DEINTERLACE | DDSCAPS2_DISCARDBACKBUFFER | DDSCAPS2_ENABLEALPHACHANNEL \
                                                    | DDSCAPS2_EXTENDEDFORMATPRIMARY | DDSCAPS2_ADDITIONALPRIMARY)

#define DDSCAPS3_NONE							0x00000000L
#define DDSCAPS3_VALID                          (DDSCAPS3_MULTISAMPLE_MASK)

#define DDSCAPS4_NONE							0x00000000L
#define DDSCAPS4_VALID                          (DDSCAPS4_NONE)

#define PALETTE_MAX_ENTRY_COUNT                 256

#define DDPFLAGS_NONE							0x00000000L

#define DDPCAPS_NONE							0x00000000L

#define DDPCAPS_INITIALIZE                      0x00000008L
#define DDPCAPS_ALL                             (DDPCAPS_4BIT | DDPCAPS_8BITENTRIES | DDPCAPS_8BIT | DDPCAPS_INITIALIZE \
                                                    | DDPCAPS_PRIMARYSURFACE | DDPCAPS_PRIMARYSURFACELEFT | DDPCAPS_ALLOW256 \
                                                    | DDPCAPS_VSYNC | DDPCAPS_1BIT | DDPCAPS_2BIT | DDPCAPS_ALPHA)

#define DDPCAPS_VALID							DDPCAPS_ALL

#define DDBLT_NONE                              0x00000000L
#define DDBLT_VALID                             (DDBLT_ALPHADEST | DDBLT_ALPHADESTCONSTOVERRIDE | DDBLT_ALPHADESTNEG | DDBLT_ALPHADESTSURFACEOVERRIDE \
                                                    | DDBLT_ALPHAEDGEBLEND | DDBLT_ALPHASRC | DDBLT_ALPHASRCCONSTOVERRIDE | DDBLT_ALPHASRCNEG \
                                                    | DDBLT_ALPHASRCSURFACEOVERRIDE | DDBLT_ASYNC | DDBLT_COLORFILL | DDBLT_DDFX | DDBLT_DDROPS \
                                                    | DDBLT_KEYDEST | DDBLT_KEYDESTOVERRIDE | DDBLT_KEYSRC | DDBLT_KEYSRCOVERRIDE | DDBLT_ROP \
                                                    | DDBLT_ROTATIONANGLE | DDBLT_ZBUFFER | DDBLT_ZBUFFERDESTCONSTOVERRIDE | DDBLT_ZBUFFERDESTOVERRIDE \
                                                    | DDBLT_ZBUFFERSRCCONSTOVERRIDE | DDBLT_ZBUFFERSRCOVERRIDE | DDBLT_WAIT | DDBLT_DEPTHFILL | DDBLT_DONOTWAIT)

#define DDBLTFAST_NONE                          DDBLTFAST_NOCOLORKEY
#define DDBLTFAST_VALID                         (DDBLTFAST_NOCOLORKEY | DDBLTFAST_SRCCOLORKEY | DDBLTFAST_DESTCOLORKEY | DDBLTFAST_WAIT | DDBLTFAST_DONOTWAIT)

#define DDCKEY_NONE                             0x00000000L
#define DDCKEY_VALID		                    (DDCKEY_COLORSPACE | DDCKEY_DESTBLT	| DDCKEY_DESTOVERLAY | DDCKEY_SRCBLT | DDCKEY_SRCOVERLAY)

#define DDLOCK_NONE                             DDLOCK_SURFACEMEMORYPTR
#define DDLOCK_VALID                            (DDLOCK_SURFACEMEMORYPTR | DDLOCK_WAIT | DDLOCK_EVENT | DDLOCK_EVENT \
                                                    | DDLOCK_WRITEONLY | DDLOCK_NOSYSLOCK | DDLOCK_NOOVERWRITE | DDLOCK_DISCARDCONTENTS \
                                                    | DDLOCK_OKTOSWAP | DDLOCK_DONOTWAIT | DDLOCK_HASVOLUMETEXTUREBOXRECT | DDLOCK_NODIRTYUPDATE)

#define DDCAPS_NONE                             0x00000000L
#define DDCAPS_ALL                              (DDCAPS_3D | DDCAPS_BLT | DDCAPS_BLTQUEUE | DDCAPS_BLTFOURCC | DDCAPS_BLTSTRETCH | DDCAPS_GDI \
                                                    | DDCAPS_OVERLAY | DDCAPS_OVERLAYFOURCC | DDCAPS_OVERLAYSTRETCH | DDCAPS_PALETTE | DDCAPS_PALETTEVSYNC \
                                                    | DDCAPS_READSCANLINE | DDCAPS_RESERVED1 | DDCAPS_VBI | DDCAPS_ZBLTS | DDCAPS_ZOVERLAYS | DDCAPS_COLORKEY \
                                                    | DDCAPS_ALPHA | DDCAPS_COLORKEYHWASSIST | DDCAPS_BLTCOLORFILL | DDCAPS_BLTDEPTHFILL | DDCAPS_CANCLIP \
                                                    | DDCAPS_CANCLIPSTRETCHED | DDCAPS_CANBLTSYSMEM)
#define DDCAPS_VALID                            (DDCAPS_3D | DDCAPS_ALIGNBOUNDARYDEST | DDCAPS_ALIGNSIZEDEST | DDCAPS_ALIGNBOUNDARYSRC \
                                                    | DDCAPS_ALIGNSIZESRC | DDCAPS_ALIGNSTRIDE | DDCAPS_BLT | DDCAPS_BLTQUEUE | DDCAPS_BLTFOURCC \
                                                    | DDCAPS_BLTSTRETCH | DDCAPS_GDI | DDCAPS_OVERLAY | DDCAPS_OVERLAYCANTCLIP | DDCAPS_OVERLAYFOURCC \
                                                    | DDCAPS_OVERLAYSTRETCH | DDCAPS_PALETTE | DDCAPS_PALETTEVSYNC | DDCAPS_READSCANLINE | DDCAPS_RESERVED1 \
                                                    | DDCAPS_VBI | DDCAPS_ZBLTS | DDCAPS_ZOVERLAYS | DDCAPS_COLORKEY | DDCAPS_ALPHA | DDCAPS_COLORKEYHWASSIST \
                                                    | DDCAPS_NOHARDWARE | DDCAPS_BLTCOLORFILL | DDCAPS_BANKSWITCHED | DDCAPS_BLTDEPTHFILL | DDCAPS_CANCLIP \
                                                    | DDCAPS_CANCLIPSTRETCHED | DDCAPS_CANBLTSYSMEM)

#define DDCAPS2_NONE                            0x00000000L
#define DDCAPS2_PUREHAL                         0x08000000L
#define DDCAPS2_ALL                             (DDCAPS2_CERTIFIED | DDCAPS2_COLORCONTROLOVERLAY | DDCAPS2_COLORCONTROLPRIMARY | DDCAPS2_CANDROPZ16BIT \
                                                    | DDCAPS2_NONLOCALVIDMEM | DDCAPS2_NOPAGELOCKREQUIRED | DDCAPS2_WIDESURFACES | DDCAPS2_CANFLIPODDEVEN | DDCAPS2_COPYFOURCC \
                                                    | DDCAPS2_PRIMARYGAMMA | DDCAPS2_CANRENDERWINDOWED | DDCAPS2_CANCALIBRATEGAMMA | DDCAPS2_FLIPNOVSYNC | DDCAPS2_CANMANAGETEXTURE \
                                                    | DDCAPS2_TEXMANINNONLOCALVIDMEM | DDCAPS2_DYNAMICTEXTURES | DDCAPS2_CANAUTOGENMIPMAP)

#define DDCAPS2_VALID                           (DDCAPS2_CERTIFIED | DDCAPS2_NO2DDURING3DSCENE | DDCAPS2_VIDEOPORT | DDCAPS2_AUTOFLIPOVERLAY | DDCAPS2_CANBOBINTERLEAVED \
                                                    | DDCAPS2_CANBOBNONINTERLEAVED | DDCAPS2_COLORCONTROLOVERLAY | DDCAPS2_COLORCONTROLPRIMARY | DDCAPS2_CANDROPZ16BIT \
                                                    | DDCAPS2_NONLOCALVIDMEM | DDCAPS2_NONLOCALVIDMEMCAPS | DDCAPS2_NOPAGELOCKREQUIRED | DDCAPS2_WIDESURFACES \
                                                    | DDCAPS2_CANFLIPODDEVEN | DDCAPS2_CANBOBHARDWARE | DDCAPS2_COPYFOURCC | DDCAPS2_PRIMARYGAMMA | DDCAPS2_CANRENDERWINDOWED \
                                                    | DDCAPS2_CANCALIBRATEGAMMA | DDCAPS2_FLIPINTERVAL | DDCAPS2_FLIPNOVSYNC | DDCAPS2_CANMANAGETEXTURE | DDCAPS2_TEXMANINNONLOCALVIDMEM \
                                                    | DDCAPS2_STEREO | DDCAPS2_SYSTONONLOCAL_AS_SYSTOLOCAL | DDCAPS2_PUREHAL | DDCAPS2_CANMANAGERESOURCE | DDCAPS2_DYNAMICTEXTURES \
                                                    | DDCAPS2_CANAUTOGENMIPMAP)

#define DDCAPS3_NONE                            0x00000000L
#define DDCAPS4_NONE                            0x00000000L

#define DDCKEYCAPS_NONE                         0x00000000L
#define DDCKEYCAPS_ALL                          (DDCKEYCAPS_DESTBLT | DDCKEYCAPS_DESTBLTCLRSPACE | DDCKEYCAPS_DESTBLTCLRSPACEYUV \
                                                    | DDCKEYCAPS_DESTBLTYUV | DDCKEYCAPS_DESTOVERLAY | DDCKEYCAPS_DESTOVERLAYCLRSPACE \
                                                    | DDCKEYCAPS_DESTOVERLAYCLRSPACEYUV | DDCKEYCAPS_DESTOVERLAYONEACTIVE | DDCKEYCAPS_DESTOVERLAYYUV \
                                                    | DDCKEYCAPS_SRCBLT | DDCKEYCAPS_SRCBLTCLRSPACE | DDCKEYCAPS_SRCBLTCLRSPACEYUV | DDCKEYCAPS_SRCBLTYUV \
                                                    | DDCKEYCAPS_SRCOVERLAY | DDCKEYCAPS_SRCOVERLAYCLRSPACE | DDCKEYCAPS_SRCOVERLAYCLRSPACEYUV \
                                                    | DDCKEYCAPS_SRCOVERLAYYUV | DDCKEYCAPS_NOCOSTOVERLAY)
#define DDCKEYCAPS_VALID                        (DDCKEYCAPS_DESTBLT | DDCKEYCAPS_DESTBLTCLRSPACE | DDCKEYCAPS_DESTBLTCLRSPACEYUV \
                                                    | DDCKEYCAPS_DESTBLTYUV | DDCKEYCAPS_DESTOVERLAY | DDCKEYCAPS_DESTOVERLAYCLRSPACE \
                                                    | DDCKEYCAPS_DESTOVERLAYCLRSPACEYUV | DDCKEYCAPS_DESTOVERLAYONEACTIVE | DDCKEYCAPS_DESTOVERLAYYUV \
                                                    | DDCKEYCAPS_SRCBLT | DDCKEYCAPS_SRCBLTCLRSPACE | DDCKEYCAPS_SRCBLTCLRSPACEYUV | DDCKEYCAPS_SRCBLTYUV \
                                                    | DDCKEYCAPS_SRCOVERLAY | DDCKEYCAPS_SRCOVERLAYCLRSPACE | DDCKEYCAPS_SRCOVERLAYCLRSPACEYUV \
                                                    | DDCKEYCAPS_SRCOVERLAYONEACTIVE | DDCKEYCAPS_SRCOVERLAYYUV | DDCKEYCAPS_NOCOSTOVERLAY)

#define DDFXCAPS_NONE                           0x00000000L
#define DDFXCAPS_ALL                            (DDFXCAPS_BLTALPHA | DDFXCAPS_OVERLAYALPHA | DDFXCAPS_OVERLAYARITHSTRETCHYN | DDFXCAPS_BLTARITHSTRETCHYN \
                                                    | DDFXCAPS_BLTARITHSTRETCHY | DDFXCAPS_BLTMIRRORLEFTRIGHT | DDFXCAPS_BLTMIRRORUPDOWN | DDFXCAPS_BLTROTATION \
                                                    | DDFXCAPS_BLTROTATION90 | DDFXCAPS_BLTSHRINKX | DDFXCAPS_BLTSHRINKXN | DDFXCAPS_BLTSHRINKY | DDFXCAPS_BLTSHRINKYN \
                                                    | DDFXCAPS_BLTSTRETCHX | DDFXCAPS_BLTSTRETCHXN | DDFXCAPS_BLTSTRETCHY | DDFXCAPS_BLTSTRETCHYN | DDFXCAPS_OVERLAYARITHSTRETCHY \
                                                    | DDFXCAPS_OVERLAYSHRINKX | DDFXCAPS_OVERLAYSHRINKXN | DDFXCAPS_OVERLAYSHRINKY | DDFXCAPS_OVERLAYSHRINKYN \
                                                    | DDFXCAPS_OVERLAYSTRETCHX | DDFXCAPS_OVERLAYSTRETCHXN | DDFXCAPS_OVERLAYSTRETCHY | DDFXCAPS_OVERLAYSTRETCHYN \
                                                    | DDFXCAPS_OVERLAYMIRRORLEFTRIGHT | DDFXCAPS_OVERLAYMIRRORUPDOWN)

#define DDFXCAPS_VALID                          (DDFXCAPS_BLTALPHA | DDFXCAPS_OVERLAYALPHA | DDFXCAPS_OVERLAYARITHSTRETCHYN | DDFXCAPS_BLTARITHSTRETCHYN \
                                                    | DDFXCAPS_BLTARITHSTRETCHY | DDFXCAPS_BLTMIRRORLEFTRIGHT | DDFXCAPS_BLTMIRRORUPDOWN | DDFXCAPS_BLTROTATION \
                                                    | DDFXCAPS_BLTROTATION90 | DDFXCAPS_BLTSHRINKX | DDFXCAPS_BLTSHRINKXN | DDFXCAPS_BLTSHRINKY | DDFXCAPS_BLTSHRINKYN \
                                                    | DDFXCAPS_BLTSTRETCHX | DDFXCAPS_BLTSTRETCHXN | DDFXCAPS_BLTSTRETCHY | DDFXCAPS_BLTSTRETCHYN | DDFXCAPS_OVERLAYARITHSTRETCHY \
                                                    | DDFXCAPS_OVERLAYSHRINKX | DDFXCAPS_OVERLAYSHRINKXN | DDFXCAPS_OVERLAYSHRINKY | DDFXCAPS_OVERLAYSHRINKYN \
                                                    | DDFXCAPS_OVERLAYSTRETCHX | DDFXCAPS_OVERLAYSTRETCHXN | DDFXCAPS_OVERLAYSTRETCHY | DDFXCAPS_OVERLAYSTRETCHYN \
                                                    | DDFXCAPS_OVERLAYMIRRORLEFTRIGHT | DDFXCAPS_OVERLAYMIRRORUPDOWN | DDFXCAPS_OVERLAYDEINTERLACE)

#define DDFXALPHACAPS_NONE                      0x00000000L

#define DDFXALPHACAPS_ALL                       (DDFXALPHACAPS_BLTALPHAEDGEBLEND | DDFXALPHACAPS_BLTALPHAPIXELS | DDFXALPHACAPS_BLTALPHAPIXELSNEG | DDFXALPHACAPS_BLTALPHASURFACES \
                                                    | DDFXALPHACAPS_BLTALPHASURFACESNEG | DDFXALPHACAPS_OVERLAYALPHAEDGEBLEND | DDFXALPHACAPS_OVERLAYALPHAPIXELS \
                                                    | DDFXALPHACAPS_OVERLAYALPHAPIXELSNEG | DDFXALPHACAPS_OVERLAYALPHASURFACES | DDFXALPHACAPS_OVERLAYALPHASURFACESNEG)

#define DDFXALPHACAPS_VALID                     DDFXALPHACAPS_ALL

#define DDSVCAPS_NONE                           0x00000000L
#define DDSVCAPS_ENIGMA                         0x00000001L
#define DDSVCAPS_FLICKER                        0x00000002L
#define DDSVCAPS_REDBLUE                        0x00000004L
#define DDSVCAPS_SPLIT                          0x00000008L

#define DDSVCAPS_VALID                          (DDSVCAPS_ENIGMA | DDSVCAPS_FLICKER | DDSVCAPS_REDBLUE | DDSVCAPS_SPLIT | DDSVCAPS_STEREOSEQUENTIAL)

#define DDOVER_NONE                             0x00000000L
#define DDOVER_VALID                            (DDOVER_ALPHADEST | DDOVER_ALPHADESTCONSTOVERRIDE | DDOVER_ALPHADESTNEG | DDOVER_ALPHADESTSURFACEOVERRIDE \
                                                    | DDOVER_ALPHAEDGEBLEND | DDOVER_ALPHASRC | DDOVER_ALPHASRCCONSTOVERRIDE | DDOVER_ALPHASRCNEG \
                                                    | DDOVER_ALPHASRCSURFACEOVERRIDE | DDOVER_HIDE | DDOVER_KEYDEST | DDOVER_KEYDESTOVERRIDE | DDOVER_KEYSRC \
                                                    | DDOVER_KEYSRCOVERRIDE | DDOVER_SHOW | DDOVER_ADDDIRTYRECT | DDOVER_REFRESHDIRTYRECTS | DDOVER_REFRESHALL \
                                                    | DDOVER_DDFX | DDOVER_AUTOFLIP | DDOVER_BOB | DDOVER_OVERRIDEBOBWEAVE | DDOVER_INTERLEAVED | DDOVER_BOBHARDWARE \
                                                    | DDOVER_ARGBSCALEFACTORS | DDOVER_DEGRADEARGBSCALING)

#define DDCOLOR_NONE                            0x00000000L
#define DDCOLOR_VALID                           (DDCOLOR_BRIGHTNESS | DDCOLOR_CONTRAST | DDCOLOR_HUE | DDCOLOR_SATURATION | DDCOLOR_SHARPNESS | DDCOLOR_GAMMA | DDCOLOR_COLORENABLE)

#define DDGGR_NONE                              0x00000000L

#define DDSGR_NONE                              0x00000000L

#define DDWAITVB_NONE                           0x00000000L
#define DDWAITVB_VALID                          (DDWAITVB_BLOCKBEGIN | DDWAITVB_BLOCKEND)
#define DDWAITVB_ALL                            (DDWAITVB_BLOCKBEGIN | DDWAITVB_BLOCKBEGINEVENT | DDWAITVB_BLOCKEND)


#define FOURCC_NONE                             0x00000000

#define DDPF_D3DFORMAT                          0x00200000

typedef int bool;

typedef int s32;
typedef unsigned int u32;

typedef float f32;
typedef double f64;

typedef char s8;
typedef unsigned char u8;

typedef short s16;
typedef unsigned short u16;

const extern GUID SUGARDRAW_DEVICE_GUID;

const extern GUID CLSID_DirectDrawFactory2;

const extern GUID IID_IDirectDrawFactory2;

#define DDERR_UNRECOGNIZEDGUID                  MAKE_DDHRESULT( 650 )
#define DDERR_NOTANOPTIMIZEDSURFACE             MAKE_DDHRESULT( 652 )
#define DDERR_ISOPTIMIZEDSURFACE                MAKE_DDHRESULT( 655 )

#define SUGARDRAW_DEVICE_FILE		            "sugar.dll"
#define SUGARDRAW_DEVICE_FILE_LENGTH            32

#define SUGARDRAW_DEVICE_NAME		            "SugarDraw Device"
#define SUGARDRAW_DEVICE_NAME_LENGTH            32

#define SUGARDRAW_DEVICE_DESCRIPTION            "SugarDraw Device Driver"
#define SUGARDRAW_DEVICE_DESCRIPTION_LENGTH     32

#define MAX_TOTAL_VIDEO_MEMORY                  (256 * 1024 * 1024)
#define MAX_VISIBLE_OVERLAY_COUNT               256

#define CompareMemory(a, b, size)               (memcmp(a, b, size) == 0)

#define EXITCODE(X)                             hr = (X); goto exit;
#define GOTO(LABEL, X)                          hr = (X); goto LABEL;

#define MAKETYPE(TYPE, X)                       \
    TYPE X;                                     \
    ZeroMemory(&X, sizeof(TYPE));

#define MAKEDEVMODEA(X)                         \
    MAKETYPE(DEVMODEA, X);                      \
    X.dmSize = sizeof(DEVMODEA);

#define MAKEDDSURFACEDESC(X)                    \
    MAKETYPE(DDSURFACEDESC, X);                 \
    X.dwSize = sizeof(DDSURFACEDESC);

#define MAKEDDSURFACEDESC2(X)                   \
    MAKETYPE(DDSURFACEDESC2, X);                \
    X.dwSize = sizeof(DDSURFACEDESC2);

#define MAKEDDPIXELFORMAT(X)                    \
    MAKETYPE(DDPIXELFORMAT, X);                 \
    X.dwSize = sizeof(DDPIXELFORMAT);

BOOL IsInsideRect(const RECT* bounds, const RECT* rect);
BOOL IsValidRect(const RECT* rect);

BOOL devmodea_equal(const DEVMODEA* mode, const DEVMODEA* value);
