#pragma once
#include "sugar.h"

typedef struct dd dd;

typedef struct idd {
    const void* self;
    sugar*      manager;
    GUID        id;
    s32         refs;
    dd*         instance;
} idd;

typedef HRESULT(SUGARCALL* IDDQUERYINTERFACE)(idd*, REFIID, LPVOID*);
typedef ULONG(SUGARCALL* IDDADDREF)(idd*);
typedef ULONG(SUGARCALL* IDDRELEASE)(idd*);
typedef HRESULT(SUGARCALL* IDDCOMPACT)(idd*);
typedef HRESULT(SUGARCALL* IDDCREATECLIPPER)(idd*, DWORD, LPDIRECTDRAWCLIPPER*, IUnknown*);
typedef HRESULT(SUGARCALL* IDDCREATEPALETTE)(idd*, DWORD, LPPALETTEENTRY, LPDIRECTDRAWPALETTE*, IUnknown*);
typedef HRESULT(SUGARCALL* IDDCREATESURFACE1)(idd*, LPDDSURFACEDESC, LPDIRECTDRAWSURFACE*, IUnknown*);
typedef HRESULT(SUGARCALL* IDDDUPLICATESURFACE1)(idd*, LPDIRECTDRAWSURFACE, LPDIRECTDRAWSURFACE*);
typedef HRESULT(SUGARCALL* IDDENUMDISPLAYMODES1)(idd*, DWORD, LPDDSURFACEDESC, LPVOID, LPDDENUMMODESCALLBACK);
typedef HRESULT(SUGARCALL* IDDENUMSURFACES1)(idd*, DWORD, LPDDSURFACEDESC, LPVOID, LPDDENUMSURFACESCALLBACK);
typedef HRESULT(SUGARCALL* IDDFLIPTOGDISURFACE)(idd*);
typedef HRESULT(SUGARCALL* IDDGETCAPS)(idd*, LPDDCAPS, LPDDCAPS);
typedef HRESULT(SUGARCALL* IDDGETDISPLAYMODE1)(idd*, LPDDSURFACEDESC);
typedef HRESULT(SUGARCALL* IDDGETFOURCCCODES)(idd*, LPDWORD, LPDWORD);
typedef HRESULT(SUGARCALL* IDDGETGDISURFACE1)(idd*, LPDIRECTDRAWSURFACE*);
typedef HRESULT(SUGARCALL* IDDGETMONITORFREQUENCY)(idd*, LPDWORD);
typedef HRESULT(SUGARCALL* IDDGETSCANLINE)(idd*, LPDWORD);
typedef HRESULT(SUGARCALL* IDDGETVERTICALBLANKSTATUS)(idd*, LPBOOL);
typedef HRESULT(SUGARCALL* IDDINITIALIZE)(idd*, GUID*);
typedef HRESULT(SUGARCALL* IDDRESTOREDISPLAYMODE)(idd*);
typedef HRESULT(SUGARCALL* IDDSETCOOPERATIVELEVEL)(idd*, HWND, DWORD);
typedef HRESULT(SUGARCALL* IDDSETDISPLAYMODE1)(idd*, DWORD, DWORD, DWORD);
typedef HRESULT(SUGARCALL* IDDWAITFORVERTICALBLANK)(idd*, DWORD, HANDLE);

typedef HRESULT(SUGARCALL* IDDSETDISPLAYMODE2)(idd*, DWORD, DWORD, DWORD, DWORD, DWORD);
typedef HRESULT(SUGARCALL* IDDGETAVAILABLEVIDMEM2)(idd*, LPDDSCAPS, LPDWORD, LPDWORD);

typedef HRESULT(SUGARCALL* IDDCREATESURFACE4)(idd*, LPDDSURFACEDESC2, LPDIRECTDRAWSURFACE4*, IUnknown*);
typedef HRESULT(SUGARCALL* IDDDUPLICATESURFACE4)(idd*, LPDIRECTDRAWSURFACE4, LPDIRECTDRAWSURFACE4*);
typedef HRESULT(SUGARCALL* IDDENUMDISPLAYMODES4)(idd*, DWORD, LPDDSURFACEDESC2, LPVOID, LPDDENUMMODESCALLBACK2);
typedef HRESULT(SUGARCALL* IDDENUMSURFACES4)(idd*, DWORD, LPDDSURFACEDESC2, LPVOID, LPDDENUMSURFACESCALLBACK2);
typedef HRESULT(SUGARCALL* IDDGETDISPLAYMODE4)(idd*, LPDDSURFACEDESC2);
typedef HRESULT(SUGARCALL* IDDGETGDISURFACE4)(idd*, LPDIRECTDRAWSURFACE4*);
typedef HRESULT(SUGARCALL* IDDGETAVAILABLEVIDMEM4)(idd*, LPDDSCAPS2, LPDWORD, LPDWORD);
typedef HRESULT(SUGARCALL* IDDGETSURFACEFROMDC4)(idd*, HDC, LPDIRECTDRAWSURFACE4*);
typedef HRESULT(SUGARCALL* IDDRESTOREALLSURFACES4)(idd*);
typedef HRESULT(SUGARCALL* IDDTESTCOOPERATIVELEVEL4)(idd*);
typedef HRESULT(SUGARCALL* IDDGETDEVICEIDENTIFIER4)(idd*, LPDDDEVICEIDENTIFIER, DWORD);

typedef HRESULT(SUGARCALL* IDDCREATESURFACE7)(idd*, LPDDSURFACEDESC2, LPDIRECTDRAWSURFACE7*, IUnknown*);
typedef HRESULT(SUGARCALL* IDDDUPLICATESURFACE7)(idd*, LPDIRECTDRAWSURFACE7, LPDIRECTDRAWSURFACE7*);
typedef HRESULT(SUGARCALL* IDDENUMSURFACES7)(idd*, DWORD, LPDDSURFACEDESC2, LPVOID, LPDDENUMSURFACESCALLBACK7);
typedef HRESULT(SUGARCALL* IDDGETGDISURFACE7)(idd*, LPDIRECTDRAWSURFACE7*);
typedef HRESULT(SUGARCALL* IDDGETSURFACEFROMDC7)(idd*, HDC, LPDIRECTDRAWSURFACE7*);
typedef HRESULT(SUGARCALL* IDDGETDEVICEIDENTIFIER7)(idd*, LPDDDEVICEIDENTIFIER2, DWORD);
typedef HRESULT(SUGARCALL* IDDSTARTMODETEST7)(idd*, LPSIZE, DWORD, DWORD);
typedef HRESULT(SUGARCALL* IDDEVALUATEMODE7)(idd*, DWORD, DWORD*);

HRESULT SUGARCALL idd_create(sugar* manager, const GUID* riid, idd** object);
VOID SUGARCALL idd_release(idd* self);

HRESULT SUGARCALL idd_query_interface(idd* self, const GUID* riid, void** object);
ULONG SUGARCALL idd_add_ref(idd* self);
ULONG SUGARCALL idd_remove_ref(idd* self);
