#pragma once
#include "sugar.h"

typedef struct dds dds;

typedef struct idds {
    const void* self;
    sugar*      manager;
    GUID        id;
    s32         refs;
    dds*        instance;
} idds;

typedef HRESULT(SUGARCALL* IDDSQUERYINTERFACE)(idds*, REFIID, LPVOID*);
typedef ULONG(SUGARCALL*   IDDSADDREF)(idds*);
typedef ULONG(SUGARCALL*   IDDSRELEASE)(idds*);
typedef HRESULT(SUGARCALL* IDDSADDATTACHEDSURFACE1)(idds*, LPDIRECTDRAWSURFACE);
typedef HRESULT(SUGARCALL* IDDSADDOVERLAYDIRTYRECT)(idds*, LPRECT);
typedef HRESULT(SUGARCALL* IDDSBLT1)(idds*, LPRECT, LPDIRECTDRAWSURFACE, LPRECT, DWORD, LPDDBLTFX);
typedef HRESULT(SUGARCALL* IDDSBLTBATCH)(idds*, LPDDBLTBATCH, DWORD, DWORD);
typedef HRESULT(SUGARCALL* IDDSBLTFAST1)(idds*, DWORD, DWORD, LPDIRECTDRAWSURFACE, LPRECT, DWORD);
typedef HRESULT(SUGARCALL* IDDSDELETEATTACHEDSURFACE1)(idds*, DWORD, LPDIRECTDRAWSURFACE);
typedef HRESULT(SUGARCALL* IDDSENUMATTACHEDSURFACES)(idds*, LPVOID, LPDDENUMSURFACESCALLBACK);
typedef HRESULT(SUGARCALL* IDDSENUMOVERLAYZORDERS)(idds*, DWORD, LPVOID, LPDDENUMSURFACESCALLBACK);
typedef HRESULT(SUGARCALL* IDDSFLIP1)(idds*, LPDIRECTDRAWSURFACE, DWORD);
typedef HRESULT(SUGARCALL* IDDSGETATTACHEDSURFACE1)(idds*, LPDDSCAPS, LPDIRECTDRAWSURFACE*);
typedef HRESULT(SUGARCALL* IDDSGETBLTSTATUS)(idds*, DWORD);
typedef HRESULT(SUGARCALL* IDDSGETCAPS1)(idds*, LPDDSCAPS);
typedef HRESULT(SUGARCALL* IDDSGETCLIPPER)(idds*, LPDIRECTDRAWCLIPPER*);
typedef HRESULT(SUGARCALL* IDDSGETCOLORKEY)(idds*, DWORD, LPDDCOLORKEY);
typedef HRESULT(SUGARCALL* IDDSGETDC)(idds*, HDC*);
typedef HRESULT(SUGARCALL* IDDSGETFLIPSTATUS)(idds*, DWORD);
typedef HRESULT(SUGARCALL* IDDSGETOVERLAYPOSITION)(idds*, LPLONG, LPLONG);
typedef HRESULT(SUGARCALL* IDDSGETPALETTE)(idds*, LPDIRECTDRAWPALETTE*);
typedef HRESULT(SUGARCALL* IDDSGETPIXELFORMAT)(idds*, LPDDPIXELFORMAT);
typedef HRESULT(SUGARCALL* IDDSGETSURFACEDESC1)(idds*, LPDDSURFACEDESC);
typedef HRESULT(SUGARCALL* IDDSINITIALIZE1)(idds*, LPDIRECTDRAW, LPDDSURFACEDESC);
typedef HRESULT(SUGARCALL* IDDSISLOST)(idds*);
typedef HRESULT(SUGARCALL* IDDSLOCK1)(idds*, LPRECT, LPDDSURFACEDESC, DWORD, HANDLE);
typedef HRESULT(SUGARCALL* IDDSRELEASEDC)(idds*, HDC);
typedef HRESULT(SUGARCALL* IDDSRESTORE)(idds*);
typedef HRESULT(SUGARCALL* IDDSSETCLIPPER)(idds*, LPDIRECTDRAWCLIPPER);
typedef HRESULT(SUGARCALL* IDDSSETCOLORKEY)(idds*, DWORD, LPDDCOLORKEY);
typedef HRESULT(SUGARCALL* IDDSSETOVERLAYPOSITION)(idds*, LONG, LONG);
typedef HRESULT(SUGARCALL* IDDSSETPALETTE)(idds*, LPDIRECTDRAWPALETTE);
typedef HRESULT(SUGARCALL* IDDSUNLOCK)(idds*, LPRECT);
typedef HRESULT(SUGARCALL* IDDSUPDATEOVERLAY1)(idds*, LPRECT, LPDIRECTDRAWSURFACE, LPRECT, DWORD, LPDDOVERLAYFX);
typedef HRESULT(SUGARCALL* IDDSUPDATEOVERLAYDISPLAY)(idds*, DWORD);
typedef HRESULT(SUGARCALL* IDDSUPDATEOVERLAYZORDER1)(idds*, DWORD, LPDIRECTDRAWSURFACE);

typedef HRESULT(SUGARCALL* IDDSADDATTACHEDSURFACE2)(idds*, LPDIRECTDRAWSURFACE2);
typedef HRESULT(SUGARCALL* IDDSBLT2)(idds*, LPRECT, LPDIRECTDRAWSURFACE2, LPRECT, DWORD, LPDDBLTFX);
typedef HRESULT(SUGARCALL* IDDSBLTFAST2)(idds*, DWORD, DWORD, LPDIRECTDRAWSURFACE2, LPRECT, DWORD);
typedef HRESULT(SUGARCALL* IDDSDELETEATTACHEDSURFACE2)(idds*, DWORD, LPDIRECTDRAWSURFACE2);
typedef HRESULT(SUGARCALL* IDDSFLIP2)(idds*, LPDIRECTDRAWSURFACE2, DWORD);
typedef HRESULT(SUGARCALL* IDDSGETATTACHEDSURFACE2)(idds*, LPDDSCAPS, LPDIRECTDRAWSURFACE2*);
typedef HRESULT(SUGARCALL* IDDSUPDATEOVERLAY2)(idds*, LPRECT, LPDIRECTDRAWSURFACE2, LPRECT, DWORD, LPDDOVERLAYFX);
typedef HRESULT(SUGARCALL* IDDSUPDATEOVERLAYZORDER2)(idds*, DWORD, LPDIRECTDRAWSURFACE2);
typedef HRESULT(SUGARCALL* IDDSGETDDINTERFACE2)(idds*, LPVOID*);
typedef HRESULT(SUGARCALL* IDDSPAGELOCK2)(idds*, DWORD);
typedef HRESULT(SUGARCALL* IDDSPAGEUNLOCK2)(idds*, DWORD);

typedef HRESULT(SUGARCALL* IDDSADDATTACHEDSURFACE3)(idds*, LPDIRECTDRAWSURFACE3);
typedef HRESULT(SUGARCALL* IDDSBLT3)(idds*, LPRECT, LPDIRECTDRAWSURFACE3, LPRECT, DWORD, LPDDBLTFX);
typedef HRESULT(SUGARCALL* IDDSBLTFAST3)(idds*, DWORD, DWORD, LPDIRECTDRAWSURFACE3, LPRECT, DWORD);
typedef HRESULT(SUGARCALL* IDDSDELETEATTACHEDSURFACE3)(idds*, DWORD, LPDIRECTDRAWSURFACE3);
typedef HRESULT(SUGARCALL* IDDSFLIP3)(idds*, LPDIRECTDRAWSURFACE3, DWORD);
typedef HRESULT(SUGARCALL* IDDSGETATTACHEDSURFACE3)(idds*, LPDDSCAPS, LPDIRECTDRAWSURFACE3*);
typedef HRESULT(SUGARCALL* IDDSUPDATEOVERLAY3)(idds*, LPRECT, LPDIRECTDRAWSURFACE3, LPRECT, DWORD, LPDDOVERLAYFX);
typedef HRESULT(SUGARCALL* IDDSUPDATEOVERLAYZORDER3)(idds*, DWORD, LPDIRECTDRAWSURFACE3);
typedef HRESULT(SUGARCALL* IDDSSETSURFACEDESC3)(idds*, LPDDSURFACEDESC, DWORD);

typedef HRESULT(SUGARCALL* IDDSADDATTACHEDSURFACE4)(idds*, LPDIRECTDRAWSURFACE4);
typedef HRESULT(SUGARCALL* IDDSBLT4)(idds*, LPRECT, LPDIRECTDRAWSURFACE4, LPRECT, DWORD, LPDDBLTFX);
typedef HRESULT(SUGARCALL* IDDSBLTFAST4)(idds*, DWORD, DWORD, LPDIRECTDRAWSURFACE4, LPRECT, DWORD);
typedef HRESULT(SUGARCALL* IDDSDELETEATTACHEDSURFACE4)(idds*, DWORD, LPDIRECTDRAWSURFACE4);
typedef HRESULT(SUGARCALL* IDDSFLIP4)(idds*, LPDIRECTDRAWSURFACE4, DWORD);
typedef HRESULT(SUGARCALL* IDDSGETATTACHEDSURFACE4)(idds*, LPDDSCAPS2, LPDIRECTDRAWSURFACE4*);
typedef HRESULT(SUGARCALL* IDDSGETCAPS4)(idds*, LPDDSCAPS2);
typedef HRESULT(SUGARCALL* IDDSGETSURFACEDESC4)(idds*, LPDDSURFACEDESC2);
typedef HRESULT(SUGARCALL* IDDSINITIALIZE4)(idds*, LPDIRECTDRAW, LPDDSURFACEDESC2);
typedef HRESULT(SUGARCALL* IDDSLOCK4)(idds*, LPRECT, LPDDSURFACEDESC2, DWORD, HANDLE);
typedef HRESULT(SUGARCALL* IDDSUPDATEOVERLAY4)(idds*, LPRECT, LPDIRECTDRAWSURFACE4, LPRECT, DWORD, LPDDOVERLAYFX);
typedef HRESULT(SUGARCALL* IDDSUPDATEOVERLAYZORDER4)(idds*, DWORD, LPDIRECTDRAWSURFACE4);
typedef HRESULT(SUGARCALL* IDDSSETSURFACEDESC4)(idds*, LPDDSURFACEDESC2, DWORD);
typedef HRESULT(SUGARCALL* IDDSSETPRIVATEDATA4)(idds*, REFGUID, LPVOID, DWORD, DWORD);
typedef HRESULT(SUGARCALL* IDDSGETPRIVATEDATA4)(idds*, REFGUID, LPVOID, LPDWORD);
typedef HRESULT(SUGARCALL* IDDSFREEPRIVATEDATA4)(idds*, REFGUID);
typedef HRESULT(SUGARCALL* IDDSGETUNIQUENESSVALUE4)(idds*, LPDWORD);
typedef HRESULT(SUGARCALL* IDDSCHANGEUNIQUENESSVALUE4)(idds*);

typedef HRESULT(SUGARCALL* IDDSADDATTACHEDSURFACE7)(idds*, LPDIRECTDRAWSURFACE7);
typedef HRESULT(SUGARCALL* IDDSBLT7)(idds*, LPRECT, LPDIRECTDRAWSURFACE7, LPRECT, DWORD, LPDDBLTFX);
typedef HRESULT(SUGARCALL* IDDSBLTFAST7)(idds*, DWORD, DWORD, LPDIRECTDRAWSURFACE7, LPRECT, DWORD);
typedef HRESULT(SUGARCALL* IDDSDELETEATTACHEDSURFACE7)(idds*, DWORD, LPDIRECTDRAWSURFACE7);
typedef HRESULT(SUGARCALL* IDDSFLIP7)(idds*, LPDIRECTDRAWSURFACE7, DWORD);
typedef HRESULT(SUGARCALL* IDDSGETATTACHEDSURFACE7)(idds*, LPDDSCAPS2, LPDIRECTDRAWSURFACE7*);
typedef HRESULT(SUGARCALL* IDDSUPDATEOVERLAY7)(idds*, LPRECT, LPDIRECTDRAWSURFACE7, LPRECT, DWORD, LPDDOVERLAYFX);
typedef HRESULT(SUGARCALL* IDDSUPDATEOVERLAYZORDER7)(idds*, DWORD, LPDIRECTDRAWSURFACE7);
typedef HRESULT(SUGARCALL* IDDSSETPRIORITY7)(idds*, DWORD);
typedef HRESULT(SUGARCALL* IDDSGETPRIORITY7)(idds*, LPDWORD);
typedef HRESULT(SUGARCALL* IDDSSETLOD7)(idds*, DWORD);
typedef HRESULT(SUGARCALL* IDDSGETLOD7)(idds*, LPDWORD);

HRESULT SUGARCALL idds_create(sugar* manager, const GUID* riid, idds** object);
void SUGARCALL idds_release(idds* self);

HRESULT SUGARCALL idds_query_interface(idds* self, const GUID* riid, void** object);
ULONG SUGARCALL idds_add_ref(idds* self);
ULONG SUGARCALL idds_remove_ref(idds* self);
